config/routes.rb
BookWriter::Application.routes.draw do
  devise_for :users

  resources :books

  resources :users

  root :to => 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :abstract, :edition, :genre, :published, :tags, :title, :user_ids

  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  attr_accessible :first_name, :last_name
  attr_accessor :login
  attr_accessible :login

  has_and_belongs_to_many :books

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_filter :authenticate_user!

  # GET /books
  # GET /books.json
  def index
    @books = current_user.books

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new
    @users = User.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
    @users = User.all
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    params[:book][:user_ids] ||= []
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
    <% if @book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

          <ul>
            <% @book.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label 'Titel' %>
      <br/>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label 'Auflage' %>
      <br/>
      <%= f.text_field :edition %>
    </div>
    <div class="field">
      <%= f.label 'Veröffentlichungsdatum' %>
      <br/>
      <%= f.date_select :published %>
    </div>
    <div class="field">
      <%= f.label 'Genre' %>
      <br/>
      <%= f.text_field :genre %>
    </div>
    <div class="field">
      <%= f.label 'Zusammenfassung' %>
      <br/>
      <%= f.text_area :abstract %>
    </div>
    <div class="field">
      <%= f.label 'Tags' %>
      <br/>
      <%= f.text_field :tags %>
    </div>
    <div class="field">
      <%= f.label 'Autoren' %>
      <br/>
      <% @users.each do |user| %>
          <div>
            <%= check_box_tag "book[user_ids][]", user.id, @book.users.include?(user) %>
            <%= user.email %>
          </div>
      <% end %>
    </div>
    <div class="actions">
      <%= f.submit 'Speichern' %>
    </div>
<% end %>

app/views/books/edit.html.erb
<h1>Buch bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Detailansicht', @book %> |
<%= link_to 'Zurück', books_path %>

app/views/books/index.html.erb
<h1>Bücher</h1>

<table>
  <tr>
    <th>Titel</th>
    <th>Auflage</th>
    <th>Veröffentlichungsdatum</th>
    <th>Genre</th>
    <th>Tags</th>
    <th>Autoren</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.edition %></td>
    <td><%= book.published %></td>
    <td><%= book.genre %></td>
    <td><%= book.tags %></td>
    <td>
      <% book.users.each do |user| %>
        <%= user.email %>
      <% end %>
    </td>
    <td><%= link_to 'Detailansicht', book %></td>
    <td><%= link_to 'Bearbeiten', edit_book_path(book) %></td>
    <td><%= link_to 'Löschen', book, method: :delete, data: { confirm: 'Sind Sie sicher?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Neues Buch anlegen', new_book_path %>

app/views/books/new.html.erb
<h1>Neues Buch anlegen</h1>

<%= render 'form' %>

<%= link_to 'Zurück', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titel:</b>
  <%= @book.title %>
</p>

<p>
  <b>Auflage:</b>
  <%= @book.edition %>
</p>

<p>
  <b>Veröffentlichungsdatum:</b>
  <%= @book.published %>
</p>

<p>
  <b>Genre:</b>
  <%= @book.genre %>
</p>

<p>
  <b>Zusammenfassung:</b>
  <%= @book.abstract %>
</p>

<p>
  <b>Tags:</b>
  <%= @book.tags %>
</p>

<p>
  <b>Autoren:</b>
<td>
  <% @book.users.each do |user| %>
      <%= user.email %>
  <% end %>
</td>
</p>


<%= link_to 'Bearbeiten', edit_book_path(@book) %> |
<%= link_to 'Zurück', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookWriter</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="top">

  <% if user_signed_in? %>
      <%= link_to "Home", books_path %> |
      <%= "Account: " + current_user.username %> |
      <%= link_to 'Mein Account', edit_user_registration_path %> |
      <%= link_to 'Meine Daten', edit_user_path(current_user) %> |
      <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
  <% end %>

</div>

<div id="layout_container">

  <div id="left">Hier kommt die TreeView rein!</div>
  <div id="content"><%= yield %></div>

</div>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Vorname" %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label "Nachname" %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit "Speichern" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Benutzerdaten ändern</h1>

<%= render 'form' %>

<%= link_to 'Detailansicht', @user %> |
<%= link_to 'Zurück', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>